# Most hooks are listed here => https://pre-commit.com/hooks.html
# Docs here => https://pre-commit.com/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: lint
        name: lint project
        language: system
        entry: make lint
