apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: demo-app-troubleshoot
spec:
  collectors:
    - clusterInfo: {}
    - clusterResources: {}
    - logs:
        name: demo-logs
        namespace: demo-app
        limits:
          maxLines: 1000
    - events:
        namespace: demo-app

  analyzers:
    # AI-Powered Analyzer
    - llm:
        checkName: "AI Diagnostic Analysis"
        collectorName: "demo-logs"
        fileName: "**/*.log"
        model: "gpt-4o-mini"
        maxFiles: 10
        priorityPatterns:
          - "error"
          - "fatal"
          - "failed"
          - "OOM"
        outcomes:
          - fail:
              when: "issue_found"
              message: |
                AI Analysis Found Critical Issues:
                {{.Summary}}

                Root Cause: {{.RootCause}}
                Affected Components: {{.AffectedPods}}
          - pass:
              message: "No critical issues detected"

    # Traditional analyzer for comparison
    - deploymentStatus:
        name: web-app
        namespace: demo-app
        outcomes:
          - fail:
              when: "< 1"
              message: "Web app deployment has no ready replicas"
          - pass:
              message: "Web app deployment is running"
