apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: my-application-name
spec:
  collectors:
  - clusterInfo:
      collectorName: my-cluster-info
  - clusterResources:
      collectorName: my-cluster-resources
  - runPod:
      name: "run-ping"
      namespace: default
      timeout: 60s
      podSpec: 
        #nodeSelector:
        #  some-label: exists
        containers:
        - name: run-ping
          image: busybox:1
          command: ["ping"]
          args: ["-w", "5", "www.google.com"]
  analyzers:
    - jsonCompare:
        checkName: Check Pod Scheduling
        fileName: run-ping/run-ping.json
        path: "status.phase"
        value: |
          "Running"
        outcomes:
          - fail:
              when: "false"
              message: The pod could not be scheduled
          - pass:
              when: "true"
              message: The pod was scheduled successfully
