# Minimal values for v1beta3-templated-from-v1beta2.yaml

kubernetes:
  enabled: false
  minVersion: "1.22.0"
  recommendedVersion: "1.29.0"

storage:
  enabled: false
  className: "default"

cluster:
  minNodes: 3
  recommendedNodes: 3
  minCPU: 4

node:
  minMemoryGi: 8
  recommendedMemoryGi: 16
  minEphemeralGi: 40
  recommendedEphemeralGi: 40

ingress:
  enabled: false
  type: "Contour"

runtime:
  enabled: false

distribution:
  enabled: false

nodeChecks:
  enabled: false
  count:
    enabled: false
  cpu:
    enabled: false
  memory:
    enabled: false
  ephemeral:
    enabled: false


