apiVersion: v1
kind: Namespace
metadata:
  name: test-oom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-hog
  namespace: test-oom
  labels:
    app: memory-hog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-hog
  template:
    metadata:
      labels:
        app: memory-hog
    spec:
      containers:
      - name: memory-consumer
        image: polinux/stress
        resources:
          limits:
            memory: "50Mi"
          requests:
            memory: "25Mi"
        command: ["stress"]
        args: ["--vm", "1", "--vm-bytes", "100M", "--vm-hang", "1"]