/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// CollectorsGetter has a method to return a CollectorInterface.
// A group's client should implement this interface.
type CollectorsGetter interface {
	Collectors(namespace string) CollectorInterface
}

// CollectorInterface has methods to work with Collector resources.
type CollectorInterface interface {
	Create(*v1beta1.Collector) (*v1beta1.Collector, error)
	Update(*v1beta1.Collector) (*v1beta1.Collector, error)
	UpdateStatus(*v1beta1.Collector) (*v1beta1.Collector, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Collector, error)
	List(opts v1.ListOptions) (*v1beta1.CollectorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Collector, err error)
	CollectorExpansion
}

// collectors implements CollectorInterface
type collectors struct {
	client rest.Interface
	ns     string
}

// newCollectors returns a Collectors
func newCollectors(c *TroubleshootV1beta1Client, namespace string) *collectors {
	return &collectors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the collector, and returns the corresponding collector object, and an error if there is any.
func (c *collectors) Get(name string, options v1.GetOptions) (result *v1beta1.Collector, err error) {
	result = &v1beta1.Collector{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("collectors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Collectors that match those selectors.
func (c *collectors) List(opts v1.ListOptions) (result *v1beta1.CollectorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.CollectorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("collectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested collectors.
func (c *collectors) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("collectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a collector and creates it.  Returns the server's representation of the collector, and an error, if there is any.
func (c *collectors) Create(collector *v1beta1.Collector) (result *v1beta1.Collector, err error) {
	result = &v1beta1.Collector{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("collectors").
		Body(collector).
		Do().
		Into(result)
	return
}

// Update takes the representation of a collector and updates it. Returns the server's representation of the collector, and an error, if there is any.
func (c *collectors) Update(collector *v1beta1.Collector) (result *v1beta1.Collector, err error) {
	result = &v1beta1.Collector{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("collectors").
		Name(collector.Name).
		Body(collector).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *collectors) UpdateStatus(collector *v1beta1.Collector) (result *v1beta1.Collector, err error) {
	result = &v1beta1.Collector{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("collectors").
		Name(collector.Name).
		SubResource("status").
		Body(collector).
		Do().
		Into(result)
	return
}

// Delete takes name of the collector and deletes it. Returns an error if one occurs.
func (c *collectors) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("collectors").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *collectors) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("collectors").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched collector.
func (c *collectors) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Collector, err error) {
	result = &v1beta1.Collector{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("collectors").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
