/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"time"

	v1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PreflightsGetter has a method to return a PreflightInterface.
// A group's client should implement this interface.
type PreflightsGetter interface {
	Preflights(namespace string) PreflightInterface
}

// PreflightInterface has methods to work with Preflight resources.
type PreflightInterface interface {
	Create(*v1beta1.Preflight) (*v1beta1.Preflight, error)
	Update(*v1beta1.Preflight) (*v1beta1.Preflight, error)
	UpdateStatus(*v1beta1.Preflight) (*v1beta1.Preflight, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1beta1.Preflight, error)
	List(opts v1.ListOptions) (*v1beta1.PreflightList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Preflight, err error)
	PreflightExpansion
}

// preflights implements PreflightInterface
type preflights struct {
	client rest.Interface
	ns     string
}

// newPreflights returns a Preflights
func newPreflights(c *TroubleshootV1beta1Client, namespace string) *preflights {
	return &preflights{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the preflight, and returns the corresponding preflight object, and an error if there is any.
func (c *preflights) Get(name string, options v1.GetOptions) (result *v1beta1.Preflight, err error) {
	result = &v1beta1.Preflight{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("preflights").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Preflights that match those selectors.
func (c *preflights) List(opts v1.ListOptions) (result *v1beta1.PreflightList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.PreflightList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("preflights").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested preflights.
func (c *preflights) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("preflights").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a preflight and creates it.  Returns the server's representation of the preflight, and an error, if there is any.
func (c *preflights) Create(preflight *v1beta1.Preflight) (result *v1beta1.Preflight, err error) {
	result = &v1beta1.Preflight{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("preflights").
		Body(preflight).
		Do().
		Into(result)
	return
}

// Update takes the representation of a preflight and updates it. Returns the server's representation of the preflight, and an error, if there is any.
func (c *preflights) Update(preflight *v1beta1.Preflight) (result *v1beta1.Preflight, err error) {
	result = &v1beta1.Preflight{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("preflights").
		Name(preflight.Name).
		Body(preflight).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *preflights) UpdateStatus(preflight *v1beta1.Preflight) (result *v1beta1.Preflight, err error) {
	result = &v1beta1.Preflight{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("preflights").
		Name(preflight.Name).
		SubResource("status").
		Body(preflight).
		Do().
		Into(result)
	return
}

// Delete takes name of the preflight and deletes it. Returns an error if one occurs.
func (c *preflights) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("preflights").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *preflights) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("preflights").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched preflight.
func (c *preflights) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.Preflight, err error) {
	result = &v1beta1.Preflight{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("preflights").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
