apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: cpu
spec:
  collectors:
    - run:
        collectorName: "ls"
        command: "ls"
        args: ["-al", "/"]
  analyzers:
    - textAnalyze:
        checkName: "check-ls"
        fileName: host-collectors/run-host/ls.txt
        regex: "Applications"
        outcomes:
          - pass:
              when: "true"
              message: "found it"
          - fail:
              when: "false"
              message: "did not find it"
