apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: sysctl
spec:
  collectors:
    - sysctl:
        collectorName: host sysctl
  analyzers:
    - sysctl:
        collectorName: host sysctl
        outcomes:
        - warn:
            when: 'kern.ostype == Darwin'
            message: "Running sysctl on a Darwin host"
        - pass:
            when: 'net.ipv4.conf.default.arp_ignore > 0'
            message: "ARP ignore is enabled for the default interfaces interfaces on the host."
