apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: packages
spec:
  collectors:
    - systemPackages:
        packages:
          - libzstd
          - nfs-common
  analyzers:
    - systemPackages:
        outcomes:
          - fail:
              when: "unavailable"
              message: Package {{ .Name }} is not installed.
          - pass:
              message: Package {{ .Name }} is installed.
