apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: packages
spec:
  collectors:
    - systemPackages:
        ubuntu:
          - open-iscsi
          - nfs-common
        rhel:
          - iscsi-initiator-utils
          - nfs-utils
        centos:
          - openssl
        amzn:
          - libzstd
        ol:
          - lvm2
  analyzers:
    - systemPackages:
        outcomes:
          - fail:
              when: "unavailable"
              message: Package {{ .Name }} is not installed.
          - pass:
              message: Package {{ .Name }} is installed.
