/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	troubleshootv1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AnalyzersGetter has a method to return a AnalyzerInterface.
// A group's client should implement this interface.
type AnalyzersGetter interface {
	Analyzers(namespace string) AnalyzerInterface
}

// AnalyzerInterface has methods to work with Analyzer resources.
type AnalyzerInterface interface {
	Create(ctx context.Context, analyzer *troubleshootv1beta1.Analyzer, opts v1.CreateOptions) (*troubleshootv1beta1.Analyzer, error)
	Update(ctx context.Context, analyzer *troubleshootv1beta1.Analyzer, opts v1.UpdateOptions) (*troubleshootv1beta1.Analyzer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, analyzer *troubleshootv1beta1.Analyzer, opts v1.UpdateOptions) (*troubleshootv1beta1.Analyzer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*troubleshootv1beta1.Analyzer, error)
	List(ctx context.Context, opts v1.ListOptions) (*troubleshootv1beta1.AnalyzerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *troubleshootv1beta1.Analyzer, err error)
	AnalyzerExpansion
}

// analyzers implements AnalyzerInterface
type analyzers struct {
	*gentype.ClientWithList[*troubleshootv1beta1.Analyzer, *troubleshootv1beta1.AnalyzerList]
}

// newAnalyzers returns a Analyzers
func newAnalyzers(c *TroubleshootV1beta1Client, namespace string) *analyzers {
	return &analyzers{
		gentype.NewClientWithList[*troubleshootv1beta1.Analyzer, *troubleshootv1beta1.AnalyzerList](
			"analyzers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *troubleshootv1beta1.Analyzer { return &troubleshootv1beta1.Analyzer{} },
			func() *troubleshootv1beta1.AnalyzerList { return &troubleshootv1beta1.AnalyzerList{} },
		),
	}
}
