/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	troubleshootv1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// PreflightsGetter has a method to return a PreflightInterface.
// A group's client should implement this interface.
type PreflightsGetter interface {
	Preflights(namespace string) PreflightInterface
}

// PreflightInterface has methods to work with Preflight resources.
type PreflightInterface interface {
	Create(ctx context.Context, preflight *troubleshootv1beta1.Preflight, opts v1.CreateOptions) (*troubleshootv1beta1.Preflight, error)
	Update(ctx context.Context, preflight *troubleshootv1beta1.Preflight, opts v1.UpdateOptions) (*troubleshootv1beta1.Preflight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, preflight *troubleshootv1beta1.Preflight, opts v1.UpdateOptions) (*troubleshootv1beta1.Preflight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*troubleshootv1beta1.Preflight, error)
	List(ctx context.Context, opts v1.ListOptions) (*troubleshootv1beta1.PreflightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *troubleshootv1beta1.Preflight, err error)
	PreflightExpansion
}

// preflights implements PreflightInterface
type preflights struct {
	*gentype.ClientWithList[*troubleshootv1beta1.Preflight, *troubleshootv1beta1.PreflightList]
}

// newPreflights returns a Preflights
func newPreflights(c *TroubleshootV1beta1Client, namespace string) *preflights {
	return &preflights{
		gentype.NewClientWithList[*troubleshootv1beta1.Preflight, *troubleshootv1beta1.PreflightList](
			"preflights",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *troubleshootv1beta1.Preflight { return &troubleshootv1beta1.Preflight{} },
			func() *troubleshootv1beta1.PreflightList { return &troubleshootv1beta1.PreflightList{} },
		),
	}
}
