/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	context "context"

	troubleshootv1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SupportBundlesGetter has a method to return a SupportBundleInterface.
// A group's client should implement this interface.
type SupportBundlesGetter interface {
	SupportBundles(namespace string) SupportBundleInterface
}

// SupportBundleInterface has methods to work with SupportBundle resources.
type SupportBundleInterface interface {
	Create(ctx context.Context, supportBundle *troubleshootv1beta1.SupportBundle, opts v1.CreateOptions) (*troubleshootv1beta1.SupportBundle, error)
	Update(ctx context.Context, supportBundle *troubleshootv1beta1.SupportBundle, opts v1.UpdateOptions) (*troubleshootv1beta1.SupportBundle, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, supportBundle *troubleshootv1beta1.SupportBundle, opts v1.UpdateOptions) (*troubleshootv1beta1.SupportBundle, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*troubleshootv1beta1.SupportBundle, error)
	List(ctx context.Context, opts v1.ListOptions) (*troubleshootv1beta1.SupportBundleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *troubleshootv1beta1.SupportBundle, err error)
	SupportBundleExpansion
}

// supportBundles implements SupportBundleInterface
type supportBundles struct {
	*gentype.ClientWithList[*troubleshootv1beta1.SupportBundle, *troubleshootv1beta1.SupportBundleList]
}

// newSupportBundles returns a SupportBundles
func newSupportBundles(c *TroubleshootV1beta1Client, namespace string) *supportBundles {
	return &supportBundles{
		gentype.NewClientWithList[*troubleshootv1beta1.SupportBundle, *troubleshootv1beta1.SupportBundleList](
			"supportbundles",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *troubleshootv1beta1.SupportBundle { return &troubleshootv1beta1.SupportBundle{} },
			func() *troubleshootv1beta1.SupportBundleList { return &troubleshootv1beta1.SupportBundleList{} },
		),
	}
}
