apiVersion: troubleshoot.sh/v1beta3
kind: Preflight
metadata:
  name: simple-no-template
spec:
  analyzers:
    - docString: |
        Title: Kubernetes Version Check
        Requirement: Kubernetes 1.19.0 or later
      clusterVersion:
        checkName: Kubernetes version
        outcomes:
          - fail:
              when: '< 1.19.0'
              message: Kubernetes version must be at least 1.19.0
          - pass:
              when: '>= 1.19.0'
              message: Kubernetes version is supported
