apiVersion: troubleshoot.sh/v1beta3
kind: SupportBundle
metadata:
  name: no-collectors
spec:
  analyzers:
    - clusterVersion:
        checkName: Kubernetes version
        outcomes:
          - pass:
              when: '>= 1.19.0'
              message: Kubernetes version is supported
