/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	troubleshootv1beta2 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta2"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// HostPreflightsGetter has a method to return a HostPreflightInterface.
// A group's client should implement this interface.
type HostPreflightsGetter interface {
	HostPreflights(namespace string) HostPreflightInterface
}

// HostPreflightInterface has methods to work with HostPreflight resources.
type HostPreflightInterface interface {
	Create(ctx context.Context, hostPreflight *troubleshootv1beta2.HostPreflight, opts v1.CreateOptions) (*troubleshootv1beta2.HostPreflight, error)
	Update(ctx context.Context, hostPreflight *troubleshootv1beta2.HostPreflight, opts v1.UpdateOptions) (*troubleshootv1beta2.HostPreflight, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hostPreflight *troubleshootv1beta2.HostPreflight, opts v1.UpdateOptions) (*troubleshootv1beta2.HostPreflight, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*troubleshootv1beta2.HostPreflight, error)
	List(ctx context.Context, opts v1.ListOptions) (*troubleshootv1beta2.HostPreflightList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *troubleshootv1beta2.HostPreflight, err error)
	HostPreflightExpansion
}

// hostPreflights implements HostPreflightInterface
type hostPreflights struct {
	*gentype.ClientWithList[*troubleshootv1beta2.HostPreflight, *troubleshootv1beta2.HostPreflightList]
}

// newHostPreflights returns a HostPreflights
func newHostPreflights(c *TroubleshootV1beta2Client, namespace string) *hostPreflights {
	return &hostPreflights{
		gentype.NewClientWithList[*troubleshootv1beta2.HostPreflight, *troubleshootv1beta2.HostPreflightList](
			"hostpreflights",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *troubleshootv1beta2.HostPreflight { return &troubleshootv1beta2.HostPreflight{} },
			func() *troubleshootv1beta2.HostPreflightList { return &troubleshootv1beta2.HostPreflightList{} },
		),
	}
}
