/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta2

import (
	context "context"

	troubleshootv1beta2 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta2"
	scheme "github.com/replicatedhq/troubleshoot/pkg/client/troubleshootclientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RedactorsGetter has a method to return a RedactorInterface.
// A group's client should implement this interface.
type RedactorsGetter interface {
	Redactors(namespace string) RedactorInterface
}

// RedactorInterface has methods to work with Redactor resources.
type RedactorInterface interface {
	Create(ctx context.Context, redactor *troubleshootv1beta2.Redactor, opts v1.CreateOptions) (*troubleshootv1beta2.Redactor, error)
	Update(ctx context.Context, redactor *troubleshootv1beta2.Redactor, opts v1.UpdateOptions) (*troubleshootv1beta2.Redactor, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, redactor *troubleshootv1beta2.Redactor, opts v1.UpdateOptions) (*troubleshootv1beta2.Redactor, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*troubleshootv1beta2.Redactor, error)
	List(ctx context.Context, opts v1.ListOptions) (*troubleshootv1beta2.RedactorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *troubleshootv1beta2.Redactor, err error)
	RedactorExpansion
}

// redactors implements RedactorInterface
type redactors struct {
	*gentype.ClientWithList[*troubleshootv1beta2.Redactor, *troubleshootv1beta2.RedactorList]
}

// newRedactors returns a Redactors
func newRedactors(c *TroubleshootV1beta2Client, namespace string) *redactors {
	return &redactors{
		gentype.NewClientWithList[*troubleshootv1beta2.Redactor, *troubleshootv1beta2.RedactorList](
			"redactors",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *troubleshootv1beta2.Redactor { return &troubleshootv1beta2.Redactor{} },
			func() *troubleshootv1beta2.RedactorList { return &troubleshootv1beta2.RedactorList{} },
		),
	}
}
