// +build !ignore_autogenerated

/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AfterCollection) DeepCopyInto(out *AfterCollection) {
	*out = *in
	if in.UploadResultsTo != nil {
		in, out := &in.UploadResultsTo, &out.UploadResultsTo
		*out = new(ResultRequest)
		**out = **in
	}
	if in.Callback != nil {
		in, out := &in.Callback, &out.Callback
		*out = new(ResultRequest)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AfterCollection.
func (in *AfterCollection) DeepCopy() *AfterCollection {
	if in == nil {
		return nil
	}
	out := new(AfterCollection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Analyze) DeepCopyInto(out *Analyze) {
	*out = *in
	if in.ClusterVersion != nil {
		in, out := &in.ClusterVersion, &out.ClusterVersion
		*out = new(ClusterVersion)
		(*in).DeepCopyInto(*out)
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(StorageClass)
		(*in).DeepCopyInto(*out)
	}
	if in.CustomResourceDefinition != nil {
		in, out := &in.CustomResourceDefinition, &out.CustomResourceDefinition
		*out = new(CustomResourceDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(Ingress)
		(*in).DeepCopyInto(*out)
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(AnalyzeSecret)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = new(ImagePullSecret)
		(*in).DeepCopyInto(*out)
	}
	if in.DeploymentStatus != nil {
		in, out := &in.DeploymentStatus, &out.DeploymentStatus
		*out = new(DeploymentStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.StatefulsetStatus != nil {
		in, out := &in.StatefulsetStatus, &out.StatefulsetStatus
		*out = new(StatefulsetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.ContainerRuntime != nil {
		in, out := &in.ContainerRuntime, &out.ContainerRuntime
		*out = new(ContainerRuntime)
		(*in).DeepCopyInto(*out)
	}
	if in.Distribution != nil {
		in, out := &in.Distribution, &out.Distribution
		*out = new(Distribution)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeResources != nil {
		in, out := &in.NodeResources, &out.NodeResources
		*out = new(NodeResources)
		(*in).DeepCopyInto(*out)
	}
	if in.TextAnalyze != nil {
		in, out := &in.TextAnalyze, &out.TextAnalyze
		*out = new(TextAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(DatabaseAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Mysql != nil {
		in, out := &in.Mysql, &out.Mysql
		*out = new(DatabaseAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(DatabaseAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.CephStatus != nil {
		in, out := &in.CephStatus, &out.CephStatus
		*out = new(CephStatusAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Longhorn != nil {
		in, out := &in.Longhorn, &out.Longhorn
		*out = new(LonghornAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.RegistryImages != nil {
		in, out := &in.RegistryImages, &out.RegistryImages
		*out = new(RegistryImagesAnalyze)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Analyze.
func (in *Analyze) DeepCopy() *Analyze {
	if in == nil {
		return nil
	}
	out := new(Analyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeMeta) DeepCopyInto(out *AnalyzeMeta) {
	*out = *in
	out.Exclude = in.Exclude
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeMeta.
func (in *AnalyzeMeta) DeepCopy() *AnalyzeMeta {
	if in == nil {
		return nil
	}
	out := new(AnalyzeMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzeSecret) DeepCopyInto(out *AnalyzeSecret) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzeSecret.
func (in *AnalyzeSecret) DeepCopy() *AnalyzeSecret {
	if in == nil {
		return nil
	}
	out := new(AnalyzeSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Analyzer) DeepCopyInto(out *Analyzer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Analyzer.
func (in *Analyzer) DeepCopy() *Analyzer {
	if in == nil {
		return nil
	}
	out := new(Analyzer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Analyzer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerList) DeepCopyInto(out *AnalyzerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Analyzer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerList.
func (in *AnalyzerList) DeepCopy() *AnalyzerList {
	if in == nil {
		return nil
	}
	out := new(AnalyzerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AnalyzerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerSpec) DeepCopyInto(out *AnalyzerSpec) {
	*out = *in
	if in.Analyzers != nil {
		in, out := &in.Analyzers, &out.Analyzers
		*out = make([]*Analyze, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Analyze)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerSpec.
func (in *AnalyzerSpec) DeepCopy() *AnalyzerSpec {
	if in == nil {
		return nil
	}
	out := new(AnalyzerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalyzerStatus) DeepCopyInto(out *AnalyzerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalyzerStatus.
func (in *AnalyzerStatus) DeepCopy() *AnalyzerStatus {
	if in == nil {
		return nil
	}
	out := new(AnalyzerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDevicesAnalyze) DeepCopyInto(out *BlockDevicesAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDevicesAnalyze.
func (in *BlockDevicesAnalyze) DeepCopy() *BlockDevicesAnalyze {
	if in == nil {
		return nil
	}
	out := new(BlockDevicesAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPU) DeepCopyInto(out *CPU) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPU.
func (in *CPU) DeepCopy() *CPU {
	if in == nil {
		return nil
	}
	out := new(CPU)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUAnalyze) DeepCopyInto(out *CPUAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUAnalyze.
func (in *CPUAnalyze) DeepCopy() *CPUAnalyze {
	if in == nil {
		return nil
	}
	out := new(CPUAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ceph) DeepCopyInto(out *Ceph) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ceph.
func (in *Ceph) DeepCopy() *Ceph {
	if in == nil {
		return nil
	}
	out := new(Ceph)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CephStatusAnalyze) DeepCopyInto(out *CephStatusAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CephStatusAnalyze.
func (in *CephStatusAnalyze) DeepCopy() *CephStatusAnalyze {
	if in == nil {
		return nil
	}
	out := new(CephStatusAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Certificate) DeepCopyInto(out *Certificate) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Certificate.
func (in *Certificate) DeepCopy() *Certificate {
	if in == nil {
		return nil
	}
	out := new(Certificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertificateAnalyze) DeepCopyInto(out *CertificateAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertificateAnalyze.
func (in *CertificateAnalyze) DeepCopy() *CertificateAnalyze {
	if in == nil {
		return nil
	}
	out := new(CertificateAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterInfo) DeepCopyInto(out *ClusterInfo) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterInfo.
func (in *ClusterInfo) DeepCopy() *ClusterInfo {
	if in == nil {
		return nil
	}
	out := new(ClusterInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterResources) DeepCopyInto(out *ClusterResources) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterResources.
func (in *ClusterResources) DeepCopy() *ClusterResources {
	if in == nil {
		return nil
	}
	out := new(ClusterResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterVersion) DeepCopyInto(out *ClusterVersion) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterVersion.
func (in *ClusterVersion) DeepCopy() *ClusterVersion {
	if in == nil {
		return nil
	}
	out := new(ClusterVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Collect) DeepCopyInto(out *Collect) {
	*out = *in
	if in.ClusterInfo != nil {
		in, out := &in.ClusterInfo, &out.ClusterInfo
		*out = new(ClusterInfo)
		**out = **in
	}
	if in.ClusterResources != nil {
		in, out := &in.ClusterResources, &out.ClusterResources
		*out = new(ClusterResources)
		**out = **in
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(Secret)
		**out = **in
	}
	if in.Logs != nil {
		in, out := &in.Logs, &out.Logs
		*out = new(Logs)
		(*in).DeepCopyInto(*out)
	}
	if in.Run != nil {
		in, out := &in.Run, &out.Run
		*out = new(Run)
		(*in).DeepCopyInto(*out)
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(Exec)
		(*in).DeepCopyInto(*out)
	}
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = new(Data)
		**out = **in
	}
	if in.Copy != nil {
		in, out := &in.Copy, &out.Copy
		*out = new(Copy)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Postgres != nil {
		in, out := &in.Postgres, &out.Postgres
		*out = new(Database)
		**out = **in
	}
	if in.Mysql != nil {
		in, out := &in.Mysql, &out.Mysql
		*out = new(Database)
		**out = **in
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(Database)
		**out = **in
	}
	if in.Collectd != nil {
		in, out := &in.Collectd, &out.Collectd
		*out = new(Collectd)
		(*in).DeepCopyInto(*out)
	}
	if in.Ceph != nil {
		in, out := &in.Ceph, &out.Ceph
		*out = new(Ceph)
		**out = **in
	}
	if in.Longhorn != nil {
		in, out := &in.Longhorn, &out.Longhorn
		*out = new(Longhorn)
		**out = **in
	}
	if in.RegistryImages != nil {
		in, out := &in.RegistryImages, &out.RegistryImages
		*out = new(RegistryImages)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Collect.
func (in *Collect) DeepCopy() *Collect {
	if in == nil {
		return nil
	}
	out := new(Collect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Collectd) DeepCopyInto(out *Collectd) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = new(ImagePullSecrets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Collectd.
func (in *Collectd) DeepCopy() *Collectd {
	if in == nil {
		return nil
	}
	out := new(Collectd)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectdAnalyze) DeepCopyInto(out *CollectdAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectdAnalyze.
func (in *CollectdAnalyze) DeepCopy() *CollectdAnalyze {
	if in == nil {
		return nil
	}
	out := new(CollectdAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Collector) DeepCopyInto(out *Collector) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Collector.
func (in *Collector) DeepCopy() *Collector {
	if in == nil {
		return nil
	}
	out := new(Collector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Collector) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorList) DeepCopyInto(out *CollectorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Collector, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorList.
func (in *CollectorList) DeepCopy() *CollectorList {
	if in == nil {
		return nil
	}
	out := new(CollectorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CollectorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorMeta) DeepCopyInto(out *CollectorMeta) {
	*out = *in
	out.Exclude = in.Exclude
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorMeta.
func (in *CollectorMeta) DeepCopy() *CollectorMeta {
	if in == nil {
		return nil
	}
	out := new(CollectorMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorSpec) DeepCopyInto(out *CollectorSpec) {
	*out = *in
	if in.Collectors != nil {
		in, out := &in.Collectors, &out.Collectors
		*out = make([]*Collect, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Collect)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.AfterCollection != nil {
		in, out := &in.AfterCollection, &out.AfterCollection
		*out = make([]*AfterCollection, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AfterCollection)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorSpec.
func (in *CollectorSpec) DeepCopy() *CollectorSpec {
	if in == nil {
		return nil
	}
	out := new(CollectorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectorStatus) DeepCopyInto(out *CollectorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectorStatus.
func (in *CollectorStatus) DeepCopy() *CollectorStatus {
	if in == nil {
		return nil
	}
	out := new(CollectorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRuntime) DeepCopyInto(out *ContainerRuntime) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRuntime.
func (in *ContainerRuntime) DeepCopy() *ContainerRuntime {
	if in == nil {
		return nil
	}
	out := new(ContainerRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Copy) DeepCopyInto(out *Copy) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Copy.
func (in *Copy) DeepCopy() *Copy {
	if in == nil {
		return nil
	}
	out := new(Copy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomResourceDefinition) DeepCopyInto(out *CustomResourceDefinition) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomResourceDefinition.
func (in *CustomResourceDefinition) DeepCopy() *CustomResourceDefinition {
	if in == nil {
		return nil
	}
	out := new(CustomResourceDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Data) DeepCopyInto(out *Data) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Data.
func (in *Data) DeepCopy() *Data {
	if in == nil {
		return nil
	}
	out := new(Data)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Database) DeepCopyInto(out *Database) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Database.
func (in *Database) DeepCopy() *Database {
	if in == nil {
		return nil
	}
	out := new(Database)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseAnalyze) DeepCopyInto(out *DatabaseAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseAnalyze.
func (in *DatabaseAnalyze) DeepCopy() *DatabaseAnalyze {
	if in == nil {
		return nil
	}
	out := new(DatabaseAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentStatus) DeepCopyInto(out *DeploymentStatus) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentStatus.
func (in *DeploymentStatus) DeepCopy() *DeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(DeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskUsage) DeepCopyInto(out *DiskUsage) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskUsage.
func (in *DiskUsage) DeepCopy() *DiskUsage {
	if in == nil {
		return nil
	}
	out := new(DiskUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskUsageAnalyze) DeepCopyInto(out *DiskUsageAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskUsageAnalyze.
func (in *DiskUsageAnalyze) DeepCopy() *DiskUsageAnalyze {
	if in == nil {
		return nil
	}
	out := new(DiskUsageAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Distribution) DeepCopyInto(out *Distribution) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Distribution.
func (in *Distribution) DeepCopy() *Distribution {
	if in == nil {
		return nil
	}
	out := new(Distribution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Exec) DeepCopyInto(out *Exec) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Exec.
func (in *Exec) DeepCopy() *Exec {
	if in == nil {
		return nil
	}
	out := new(Exec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FileSelector) DeepCopyInto(out *FileSelector) {
	*out = *in
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FileSelector.
func (in *FileSelector) DeepCopy() *FileSelector {
	if in == nil {
		return nil
	}
	out := new(FileSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemPerformance) DeepCopyInto(out *FilesystemPerformance) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemPerformance.
func (in *FilesystemPerformance) DeepCopy() *FilesystemPerformance {
	if in == nil {
		return nil
	}
	out := new(FilesystemPerformance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilesystemPerformanceAnalyze) DeepCopyInto(out *FilesystemPerformanceAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilesystemPerformanceAnalyze.
func (in *FilesystemPerformanceAnalyze) DeepCopy() *FilesystemPerformanceAnalyze {
	if in == nil {
		return nil
	}
	out := new(FilesystemPerformanceAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Get) DeepCopyInto(out *Get) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Get.
func (in *Get) DeepCopy() *Get {
	if in == nil {
		return nil
	}
	out := new(Get)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTP) DeepCopyInto(out *HTTP) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.Get != nil {
		in, out := &in.Get, &out.Get
		*out = new(Get)
		(*in).DeepCopyInto(*out)
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = new(Post)
		(*in).DeepCopyInto(*out)
	}
	if in.Put != nil {
		in, out := &in.Put, &out.Put
		*out = new(Put)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTP.
func (in *HTTP) DeepCopy() *HTTP {
	if in == nil {
		return nil
	}
	out := new(HTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPAnalyze) DeepCopyInto(out *HTTPAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPAnalyze.
func (in *HTTPAnalyze) DeepCopy() *HTTPAnalyze {
	if in == nil {
		return nil
	}
	out := new(HTTPAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancer) DeepCopyInto(out *HTTPLoadBalancer) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancer.
func (in *HTTPLoadBalancer) DeepCopy() *HTTPLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPLoadBalancerAnalyze) DeepCopyInto(out *HTTPLoadBalancerAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPLoadBalancerAnalyze.
func (in *HTTPLoadBalancerAnalyze) DeepCopy() *HTTPLoadBalancerAnalyze {
	if in == nil {
		return nil
	}
	out := new(HTTPLoadBalancerAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostAnalyze) DeepCopyInto(out *HostAnalyze) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPUAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPLoadBalancer != nil {
		in, out := &in.TCPLoadBalancer, &out.TCPLoadBalancer
		*out = new(TCPLoadBalancerAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPLoadBalancer != nil {
		in, out := &in.HTTPLoadBalancer, &out.HTTPLoadBalancer
		*out = new(HTTPLoadBalancerAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.DiskUsage != nil {
		in, out := &in.DiskUsage, &out.DiskUsage
		*out = new(DiskUsageAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(MemoryAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPPortStatus != nil {
		in, out := &in.TCPPortStatus, &out.TCPPortStatus
		*out = new(TCPPortStatusAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(TimeAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockDevices != nil {
		in, out := &in.BlockDevices, &out.BlockDevices
		*out = new(BlockDevicesAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelModules != nil {
		in, out := &in.KernelModules, &out.KernelModules
		*out = new(KernelModulesAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.TCPConnect != nil {
		in, out := &in.TCPConnect, &out.TCPConnect
		*out = new(TCPConnectAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.IPV4Interfaces != nil {
		in, out := &in.IPV4Interfaces, &out.IPV4Interfaces
		*out = new(IPV4InterfacesAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.FilesystemPerformance != nil {
		in, out := &in.FilesystemPerformance, &out.FilesystemPerformance
		*out = new(FilesystemPerformanceAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(CertificateAnalyze)
		(*in).DeepCopyInto(*out)
	}
	if in.HostServices != nil {
		in, out := &in.HostServices, &out.HostServices
		*out = new(HostServicesAnalyze)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostAnalyze.
func (in *HostAnalyze) DeepCopy() *HostAnalyze {
	if in == nil {
		return nil
	}
	out := new(HostAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostBlockDevices) DeepCopyInto(out *HostBlockDevices) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostBlockDevices.
func (in *HostBlockDevices) DeepCopy() *HostBlockDevices {
	if in == nil {
		return nil
	}
	out := new(HostBlockDevices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCollect) DeepCopyInto(out *HostCollect) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		*out = new(CPU)
		**out = **in
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		*out = new(Memory)
		**out = **in
	}
	if in.TCPLoadBalancer != nil {
		in, out := &in.TCPLoadBalancer, &out.TCPLoadBalancer
		*out = new(TCPLoadBalancer)
		**out = **in
	}
	if in.HTTPLoadBalancer != nil {
		in, out := &in.HTTPLoadBalancer, &out.HTTPLoadBalancer
		*out = new(HTTPLoadBalancer)
		**out = **in
	}
	if in.TCPPortStatus != nil {
		in, out := &in.TCPPortStatus, &out.TCPPortStatus
		*out = new(TCPPortStatus)
		**out = **in
	}
	if in.Kubernetes != nil {
		in, out := &in.Kubernetes, &out.Kubernetes
		*out = new(Kubernetes)
		**out = **in
	}
	if in.IPV4Interfaces != nil {
		in, out := &in.IPV4Interfaces, &out.IPV4Interfaces
		*out = new(IPV4Interfaces)
		**out = **in
	}
	if in.DiskUsage != nil {
		in, out := &in.DiskUsage, &out.DiskUsage
		*out = new(DiskUsage)
		**out = **in
	}
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HostHTTP)
		(*in).DeepCopyInto(*out)
	}
	if in.Time != nil {
		in, out := &in.Time, &out.Time
		*out = new(HostTime)
		**out = **in
	}
	if in.BlockDevices != nil {
		in, out := &in.BlockDevices, &out.BlockDevices
		*out = new(HostBlockDevices)
		**out = **in
	}
	if in.KernelModules != nil {
		in, out := &in.KernelModules, &out.KernelModules
		*out = new(HostKernelModules)
		**out = **in
	}
	if in.TCPConnect != nil {
		in, out := &in.TCPConnect, &out.TCPConnect
		*out = new(TCPConnect)
		**out = **in
	}
	if in.FilesystemPerformance != nil {
		in, out := &in.FilesystemPerformance, &out.FilesystemPerformance
		*out = new(FilesystemPerformance)
		**out = **in
	}
	if in.Certificate != nil {
		in, out := &in.Certificate, &out.Certificate
		*out = new(Certificate)
		**out = **in
	}
	if in.HostServices != nil {
		in, out := &in.HostServices, &out.HostServices
		*out = new(HostServices)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCollect.
func (in *HostCollect) DeepCopy() *HostCollect {
	if in == nil {
		return nil
	}
	out := new(HostCollect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostCollectorMeta) DeepCopyInto(out *HostCollectorMeta) {
	*out = *in
	out.Exclude = in.Exclude
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostCollectorMeta.
func (in *HostCollectorMeta) DeepCopy() *HostCollectorMeta {
	if in == nil {
		return nil
	}
	out := new(HostCollectorMeta)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostHTTP) DeepCopyInto(out *HostHTTP) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
	if in.Get != nil {
		in, out := &in.Get, &out.Get
		*out = new(Get)
		(*in).DeepCopyInto(*out)
	}
	if in.Post != nil {
		in, out := &in.Post, &out.Post
		*out = new(Post)
		(*in).DeepCopyInto(*out)
	}
	if in.Put != nil {
		in, out := &in.Put, &out.Put
		*out = new(Put)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostHTTP.
func (in *HostHTTP) DeepCopy() *HostHTTP {
	if in == nil {
		return nil
	}
	out := new(HostHTTP)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostKernelModules) DeepCopyInto(out *HostKernelModules) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostKernelModules.
func (in *HostKernelModules) DeepCopy() *HostKernelModules {
	if in == nil {
		return nil
	}
	out := new(HostKernelModules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPreflight) DeepCopyInto(out *HostPreflight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPreflight.
func (in *HostPreflight) DeepCopy() *HostPreflight {
	if in == nil {
		return nil
	}
	out := new(HostPreflight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostPreflight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPreflightList) DeepCopyInto(out *HostPreflightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HostPreflight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPreflightList.
func (in *HostPreflightList) DeepCopy() *HostPreflightList {
	if in == nil {
		return nil
	}
	out := new(HostPreflightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HostPreflightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPreflightSpec) DeepCopyInto(out *HostPreflightSpec) {
	*out = *in
	if in.Collectors != nil {
		in, out := &in.Collectors, &out.Collectors
		*out = make([]*HostCollect, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HostCollect)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Analyzers != nil {
		in, out := &in.Analyzers, &out.Analyzers
		*out = make([]*HostAnalyze, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(HostAnalyze)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPreflightSpec.
func (in *HostPreflightSpec) DeepCopy() *HostPreflightSpec {
	if in == nil {
		return nil
	}
	out := new(HostPreflightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostPreflightStatus) DeepCopyInto(out *HostPreflightStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostPreflightStatus.
func (in *HostPreflightStatus) DeepCopy() *HostPreflightStatus {
	if in == nil {
		return nil
	}
	out := new(HostPreflightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostServices) DeepCopyInto(out *HostServices) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostServices.
func (in *HostServices) DeepCopy() *HostServices {
	if in == nil {
		return nil
	}
	out := new(HostServices)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostServicesAnalyze) DeepCopyInto(out *HostServicesAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostServicesAnalyze.
func (in *HostServicesAnalyze) DeepCopy() *HostServicesAnalyze {
	if in == nil {
		return nil
	}
	out := new(HostServicesAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostTime) DeepCopyInto(out *HostTime) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostTime.
func (in *HostTime) DeepCopy() *HostTime {
	if in == nil {
		return nil
	}
	out := new(HostTime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPV4Interfaces) DeepCopyInto(out *IPV4Interfaces) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPV4Interfaces.
func (in *IPV4Interfaces) DeepCopy() *IPV4Interfaces {
	if in == nil {
		return nil
	}
	out := new(IPV4Interfaces)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPV4InterfacesAnalyze) DeepCopyInto(out *IPV4InterfacesAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPV4InterfacesAnalyze.
func (in *IPV4InterfacesAnalyze) DeepCopy() *IPV4InterfacesAnalyze {
	if in == nil {
		return nil
	}
	out := new(IPV4InterfacesAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecret) DeepCopyInto(out *ImagePullSecret) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecret.
func (in *ImagePullSecret) DeepCopy() *ImagePullSecret {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImagePullSecrets) DeepCopyInto(out *ImagePullSecrets) {
	*out = *in
	if in.Data != nil {
		in, out := &in.Data, &out.Data
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImagePullSecrets.
func (in *ImagePullSecrets) DeepCopy() *ImagePullSecrets {
	if in == nil {
		return nil
	}
	out := new(ImagePullSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Ingress) DeepCopyInto(out *Ingress) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Ingress.
func (in *Ingress) DeepCopy() *Ingress {
	if in == nil {
		return nil
	}
	out := new(Ingress)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KernelModulesAnalyze) DeepCopyInto(out *KernelModulesAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KernelModulesAnalyze.
func (in *KernelModulesAnalyze) DeepCopy() *KernelModulesAnalyze {
	if in == nil {
		return nil
	}
	out := new(KernelModulesAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Kubernetes) DeepCopyInto(out *Kubernetes) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Kubernetes.
func (in *Kubernetes) DeepCopy() *Kubernetes {
	if in == nil {
		return nil
	}
	out := new(Kubernetes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogLimits) DeepCopyInto(out *LogLimits) {
	*out = *in
	in.SinceTime.DeepCopyInto(&out.SinceTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogLimits.
func (in *LogLimits) DeepCopy() *LogLimits {
	if in == nil {
		return nil
	}
	out := new(LogLimits)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logs) DeepCopyInto(out *Logs) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ContainerNames != nil {
		in, out := &in.ContainerNames, &out.ContainerNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(LogLimits)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logs.
func (in *Logs) DeepCopy() *Logs {
	if in == nil {
		return nil
	}
	out := new(Logs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Longhorn) DeepCopyInto(out *Longhorn) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Longhorn.
func (in *Longhorn) DeepCopy() *Longhorn {
	if in == nil {
		return nil
	}
	out := new(Longhorn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LonghornAnalyze) DeepCopyInto(out *LonghornAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LonghornAnalyze.
func (in *LonghornAnalyze) DeepCopy() *LonghornAnalyze {
	if in == nil {
		return nil
	}
	out := new(LonghornAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Memory) DeepCopyInto(out *Memory) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Memory.
func (in *Memory) DeepCopy() *Memory {
	if in == nil {
		return nil
	}
	out := new(Memory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryAnalyze) DeepCopyInto(out *MemoryAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryAnalyze.
func (in *MemoryAnalyze) DeepCopy() *MemoryAnalyze {
	if in == nil {
		return nil
	}
	out := new(MemoryAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceFilters) DeepCopyInto(out *NodeResourceFilters) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(NodeResourceSelectors)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceFilters.
func (in *NodeResourceFilters) DeepCopy() *NodeResourceFilters {
	if in == nil {
		return nil
	}
	out := new(NodeResourceFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResourceSelectors) DeepCopyInto(out *NodeResourceSelectors) {
	*out = *in
	if in.MatchLabel != nil {
		in, out := &in.MatchLabel, &out.MatchLabel
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResourceSelectors.
func (in *NodeResourceSelectors) DeepCopy() *NodeResourceSelectors {
	if in == nil {
		return nil
	}
	out := new(NodeResourceSelectors)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeResources) DeepCopyInto(out *NodeResources) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(NodeResourceFilters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeResources.
func (in *NodeResources) DeepCopy() *NodeResources {
	if in == nil {
		return nil
	}
	out := new(NodeResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Outcome) DeepCopyInto(out *Outcome) {
	*out = *in
	if in.Fail != nil {
		in, out := &in.Fail, &out.Fail
		*out = new(SingleOutcome)
		**out = **in
	}
	if in.Warn != nil {
		in, out := &in.Warn, &out.Warn
		*out = new(SingleOutcome)
		**out = **in
	}
	if in.Pass != nil {
		in, out := &in.Pass, &out.Pass
		*out = new(SingleOutcome)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Outcome.
func (in *Outcome) DeepCopy() *Outcome {
	if in == nil {
		return nil
	}
	out := new(Outcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Post) DeepCopyInto(out *Post) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Post.
func (in *Post) DeepCopy() *Post {
	if in == nil {
		return nil
	}
	out := new(Post)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Preflight) DeepCopyInto(out *Preflight) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Preflight.
func (in *Preflight) DeepCopy() *Preflight {
	if in == nil {
		return nil
	}
	out := new(Preflight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Preflight) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreflightList) DeepCopyInto(out *PreflightList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Preflight, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreflightList.
func (in *PreflightList) DeepCopy() *PreflightList {
	if in == nil {
		return nil
	}
	out := new(PreflightList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PreflightList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreflightSpec) DeepCopyInto(out *PreflightSpec) {
	*out = *in
	if in.Collectors != nil {
		in, out := &in.Collectors, &out.Collectors
		*out = make([]*Collect, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Collect)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Analyzers != nil {
		in, out := &in.Analyzers, &out.Analyzers
		*out = make([]*Analyze, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Analyze)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreflightSpec.
func (in *PreflightSpec) DeepCopy() *PreflightSpec {
	if in == nil {
		return nil
	}
	out := new(PreflightSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreflightStatus) DeepCopyInto(out *PreflightStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreflightStatus.
func (in *PreflightStatus) DeepCopy() *PreflightStatus {
	if in == nil {
		return nil
	}
	out := new(PreflightStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Put) DeepCopyInto(out *Put) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Put.
func (in *Put) DeepCopy() *Put {
	if in == nil {
		return nil
	}
	out := new(Put)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redact) DeepCopyInto(out *Redact) {
	*out = *in
	in.FileSelector.DeepCopyInto(&out.FileSelector)
	in.Removals.DeepCopyInto(&out.Removals)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redact.
func (in *Redact) DeepCopy() *Redact {
	if in == nil {
		return nil
	}
	out := new(Redact)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Redactor) DeepCopyInto(out *Redactor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Redactor.
func (in *Redactor) DeepCopy() *Redactor {
	if in == nil {
		return nil
	}
	out := new(Redactor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Redactor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactorList) DeepCopyInto(out *RedactorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Redactor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactorList.
func (in *RedactorList) DeepCopy() *RedactorList {
	if in == nil {
		return nil
	}
	out := new(RedactorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RedactorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactorSpec) DeepCopyInto(out *RedactorSpec) {
	*out = *in
	if in.Redactors != nil {
		in, out := &in.Redactors, &out.Redactors
		*out = make([]*Redact, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Redact)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactorSpec.
func (in *RedactorSpec) DeepCopy() *RedactorSpec {
	if in == nil {
		return nil
	}
	out := new(RedactorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedactorStatus) DeepCopyInto(out *RedactorStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedactorStatus.
func (in *RedactorStatus) DeepCopy() *RedactorStatus {
	if in == nil {
		return nil
	}
	out := new(RedactorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Regex) DeepCopyInto(out *Regex) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Regex.
func (in *Regex) DeepCopy() *Regex {
	if in == nil {
		return nil
	}
	out := new(Regex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryImages) DeepCopyInto(out *RegistryImages) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.Images != nil {
		in, out := &in.Images, &out.Images
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = new(ImagePullSecrets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryImages.
func (in *RegistryImages) DeepCopy() *RegistryImages {
	if in == nil {
		return nil
	}
	out := new(RegistryImages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegistryImagesAnalyze) DeepCopyInto(out *RegistryImagesAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegistryImagesAnalyze.
func (in *RegistryImagesAnalyze) DeepCopy() *RegistryImagesAnalyze {
	if in == nil {
		return nil
	}
	out := new(RegistryImagesAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Removals) DeepCopyInto(out *Removals) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Regex != nil {
		in, out := &in.Regex, &out.Regex
		*out = make([]Regex, len(*in))
		copy(*out, *in)
	}
	if in.YamlPath != nil {
		in, out := &in.YamlPath, &out.YamlPath
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Removals.
func (in *Removals) DeepCopy() *Removals {
	if in == nil {
		return nil
	}
	out := new(Removals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResultRequest) DeepCopyInto(out *ResultRequest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResultRequest.
func (in *ResultRequest) DeepCopy() *ResultRequest {
	if in == nil {
		return nil
	}
	out := new(ResultRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Run) DeepCopyInto(out *Run) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImagePullSecret != nil {
		in, out := &in.ImagePullSecret, &out.ImagePullSecret
		*out = new(ImagePullSecrets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Run.
func (in *Run) DeepCopy() *Run {
	if in == nil {
		return nil
	}
	out := new(Run)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Secret) DeepCopyInto(out *Secret) {
	*out = *in
	out.CollectorMeta = in.CollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Secret.
func (in *Secret) DeepCopy() *Secret {
	if in == nil {
		return nil
	}
	out := new(Secret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SingleOutcome) DeepCopyInto(out *SingleOutcome) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SingleOutcome.
func (in *SingleOutcome) DeepCopy() *SingleOutcome {
	if in == nil {
		return nil
	}
	out := new(SingleOutcome)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulsetStatus) DeepCopyInto(out *StatefulsetStatus) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulsetStatus.
func (in *StatefulsetStatus) DeepCopy() *StatefulsetStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulsetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageClass) DeepCopyInto(out *StorageClass) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageClass.
func (in *StorageClass) DeepCopy() *StorageClass {
	if in == nil {
		return nil
	}
	out := new(StorageClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportBundle) DeepCopyInto(out *SupportBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportBundle.
func (in *SupportBundle) DeepCopy() *SupportBundle {
	if in == nil {
		return nil
	}
	out := new(SupportBundle)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupportBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportBundleList) DeepCopyInto(out *SupportBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SupportBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportBundleList.
func (in *SupportBundleList) DeepCopy() *SupportBundleList {
	if in == nil {
		return nil
	}
	out := new(SupportBundleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupportBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportBundleSpec) DeepCopyInto(out *SupportBundleSpec) {
	*out = *in
	if in.AfterCollection != nil {
		in, out := &in.AfterCollection, &out.AfterCollection
		*out = make([]*AfterCollection, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(AfterCollection)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Collectors != nil {
		in, out := &in.Collectors, &out.Collectors
		*out = make([]*Collect, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Collect)
				(*in).DeepCopyInto(*out)
			}
		}
	}
	if in.Analyzers != nil {
		in, out := &in.Analyzers, &out.Analyzers
		*out = make([]*Analyze, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Analyze)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportBundleSpec.
func (in *SupportBundleSpec) DeepCopy() *SupportBundleSpec {
	if in == nil {
		return nil
	}
	out := new(SupportBundleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportBundleStatus) DeepCopyInto(out *SupportBundleStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportBundleStatus.
func (in *SupportBundleStatus) DeepCopy() *SupportBundleStatus {
	if in == nil {
		return nil
	}
	out := new(SupportBundleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportBundleVersion) DeepCopyInto(out *SupportBundleVersion) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportBundleVersion.
func (in *SupportBundleVersion) DeepCopy() *SupportBundleVersion {
	if in == nil {
		return nil
	}
	out := new(SupportBundleVersion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupportBundleVersionSpec) DeepCopyInto(out *SupportBundleVersionSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupportBundleVersionSpec.
func (in *SupportBundleVersionSpec) DeepCopy() *SupportBundleVersionSpec {
	if in == nil {
		return nil
	}
	out := new(SupportBundleVersionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPConnect) DeepCopyInto(out *TCPConnect) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPConnect.
func (in *TCPConnect) DeepCopy() *TCPConnect {
	if in == nil {
		return nil
	}
	out := new(TCPConnect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPConnectAnalyze) DeepCopyInto(out *TCPConnectAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPConnectAnalyze.
func (in *TCPConnectAnalyze) DeepCopy() *TCPConnectAnalyze {
	if in == nil {
		return nil
	}
	out := new(TCPConnectAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPLoadBalancer) DeepCopyInto(out *TCPLoadBalancer) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPLoadBalancer.
func (in *TCPLoadBalancer) DeepCopy() *TCPLoadBalancer {
	if in == nil {
		return nil
	}
	out := new(TCPLoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPLoadBalancerAnalyze) DeepCopyInto(out *TCPLoadBalancerAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPLoadBalancerAnalyze.
func (in *TCPLoadBalancerAnalyze) DeepCopy() *TCPLoadBalancerAnalyze {
	if in == nil {
		return nil
	}
	out := new(TCPLoadBalancerAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPPortStatus) DeepCopyInto(out *TCPPortStatus) {
	*out = *in
	out.HostCollectorMeta = in.HostCollectorMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPPortStatus.
func (in *TCPPortStatus) DeepCopy() *TCPPortStatus {
	if in == nil {
		return nil
	}
	out := new(TCPPortStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TCPPortStatusAnalyze) DeepCopyInto(out *TCPPortStatusAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TCPPortStatusAnalyze.
func (in *TCPPortStatusAnalyze) DeepCopy() *TCPPortStatusAnalyze {
	if in == nil {
		return nil
	}
	out := new(TCPPortStatusAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TextAnalyze) DeepCopyInto(out *TextAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TextAnalyze.
func (in *TextAnalyze) DeepCopy() *TextAnalyze {
	if in == nil {
		return nil
	}
	out := new(TextAnalyze)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeAnalyze) DeepCopyInto(out *TimeAnalyze) {
	*out = *in
	out.AnalyzeMeta = in.AnalyzeMeta
	if in.Outcomes != nil {
		in, out := &in.Outcomes, &out.Outcomes
		*out = make([]*Outcome, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(Outcome)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeAnalyze.
func (in *TimeAnalyze) DeepCopy() *TimeAnalyze {
	if in == nil {
		return nil
	}
	out := new(TimeAnalyze)
	in.DeepCopyInto(out)
	return out
}
