FROM debian:buster
WORKDIR /

RUN apt-get -qq update \
 && apt-get -qq -y install \
    ca-certificates

COPY troubleshoot /troubleshoot/troubleshoot
COPY collector /troubleshoot/collector
COPY preflight /troubleshoot/preflight

ENV PATH="/troubleshoot:${PATH}"

