FROM debian:buster
WORKDIR /

RUN apt-get -qq update \
 && apt-get -qq -y install \
    ca-certificates

COPY preflight /preflight/preflight
COPY collector /preflight/collector

ENV PATH="/preflight:${PATH}"

