/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePreflightJobs implements PreflightJobInterface
type FakePreflightJobs struct {
	Fake *FakeTroubleshootV1beta1
	ns   string
}

var preflightjobsResource = schema.GroupVersionResource{Group: "troubleshoot.replicated.com", Version: "v1beta1", Resource: "preflightjobs"}

var preflightjobsKind = schema.GroupVersionKind{Group: "troubleshoot.replicated.com", Version: "v1beta1", Kind: "PreflightJob"}

// Get takes name of the preflightJob, and returns the corresponding preflightJob object, and an error if there is any.
func (c *FakePreflightJobs) Get(name string, options v1.GetOptions) (result *v1beta1.PreflightJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(preflightjobsResource, c.ns, name), &v1beta1.PreflightJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PreflightJob), err
}

// List takes label and field selectors, and returns the list of PreflightJobs that match those selectors.
func (c *FakePreflightJobs) List(opts v1.ListOptions) (result *v1beta1.PreflightJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(preflightjobsResource, preflightjobsKind, c.ns, opts), &v1beta1.PreflightJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.PreflightJobList{ListMeta: obj.(*v1beta1.PreflightJobList).ListMeta}
	for _, item := range obj.(*v1beta1.PreflightJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested preflightJobs.
func (c *FakePreflightJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(preflightjobsResource, c.ns, opts))

}

// Create takes the representation of a preflightJob and creates it.  Returns the server's representation of the preflightJob, and an error, if there is any.
func (c *FakePreflightJobs) Create(preflightJob *v1beta1.PreflightJob) (result *v1beta1.PreflightJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(preflightjobsResource, c.ns, preflightJob), &v1beta1.PreflightJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PreflightJob), err
}

// Update takes the representation of a preflightJob and updates it. Returns the server's representation of the preflightJob, and an error, if there is any.
func (c *FakePreflightJobs) Update(preflightJob *v1beta1.PreflightJob) (result *v1beta1.PreflightJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(preflightjobsResource, c.ns, preflightJob), &v1beta1.PreflightJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PreflightJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePreflightJobs) UpdateStatus(preflightJob *v1beta1.PreflightJob) (*v1beta1.PreflightJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(preflightjobsResource, "status", c.ns, preflightJob), &v1beta1.PreflightJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PreflightJob), err
}

// Delete takes name of the preflightJob and deletes it. Returns an error if one occurs.
func (c *FakePreflightJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(preflightjobsResource, c.ns, name), &v1beta1.PreflightJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePreflightJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(preflightjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.PreflightJobList{})
	return err
}

// Patch applies the patch and returns the patched preflightJob.
func (c *FakePreflightJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.PreflightJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(preflightjobsResource, c.ns, name, pt, data, subresources...), &v1beta1.PreflightJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.PreflightJob), err
}
