/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAnalyzerJobs implements AnalyzerJobInterface
type FakeAnalyzerJobs struct {
	Fake *FakeTroubleshootV1beta1
	ns   string
}

var analyzerjobsResource = schema.GroupVersionResource{Group: "troubleshoot.replicated.com", Version: "v1beta1", Resource: "analyzerjobs"}

var analyzerjobsKind = schema.GroupVersionKind{Group: "troubleshoot.replicated.com", Version: "v1beta1", Kind: "AnalyzerJob"}

// Get takes name of the analyzerJob, and returns the corresponding analyzerJob object, and an error if there is any.
func (c *FakeAnalyzerJobs) Get(name string, options v1.GetOptions) (result *v1beta1.AnalyzerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(analyzerjobsResource, c.ns, name), &v1beta1.AnalyzerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AnalyzerJob), err
}

// List takes label and field selectors, and returns the list of AnalyzerJobs that match those selectors.
func (c *FakeAnalyzerJobs) List(opts v1.ListOptions) (result *v1beta1.AnalyzerJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(analyzerjobsResource, analyzerjobsKind, c.ns, opts), &v1beta1.AnalyzerJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.AnalyzerJobList{ListMeta: obj.(*v1beta1.AnalyzerJobList).ListMeta}
	for _, item := range obj.(*v1beta1.AnalyzerJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested analyzerJobs.
func (c *FakeAnalyzerJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(analyzerjobsResource, c.ns, opts))

}

// Create takes the representation of a analyzerJob and creates it.  Returns the server's representation of the analyzerJob, and an error, if there is any.
func (c *FakeAnalyzerJobs) Create(analyzerJob *v1beta1.AnalyzerJob) (result *v1beta1.AnalyzerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(analyzerjobsResource, c.ns, analyzerJob), &v1beta1.AnalyzerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AnalyzerJob), err
}

// Update takes the representation of a analyzerJob and updates it. Returns the server's representation of the analyzerJob, and an error, if there is any.
func (c *FakeAnalyzerJobs) Update(analyzerJob *v1beta1.AnalyzerJob) (result *v1beta1.AnalyzerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(analyzerjobsResource, c.ns, analyzerJob), &v1beta1.AnalyzerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AnalyzerJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAnalyzerJobs) UpdateStatus(analyzerJob *v1beta1.AnalyzerJob) (*v1beta1.AnalyzerJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(analyzerjobsResource, "status", c.ns, analyzerJob), &v1beta1.AnalyzerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AnalyzerJob), err
}

// Delete takes name of the analyzerJob and deletes it. Returns an error if one occurs.
func (c *FakeAnalyzerJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(analyzerjobsResource, c.ns, name), &v1beta1.AnalyzerJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAnalyzerJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(analyzerjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.AnalyzerJobList{})
	return err
}

// Patch applies the patch and returns the patched analyzerJob.
func (c *FakeAnalyzerJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.AnalyzerJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(analyzerjobsResource, c.ns, name, pt, data, subresources...), &v1beta1.AnalyzerJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.AnalyzerJob), err
}
