/*
Copyright 2019 Replicated, Inc..

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1beta1 "github.com/replicatedhq/troubleshoot/pkg/apis/troubleshoot/v1beta1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCollectorJobs implements CollectorJobInterface
type FakeCollectorJobs struct {
	Fake *FakeTroubleshootV1beta1
	ns   string
}

var collectorjobsResource = schema.GroupVersionResource{Group: "troubleshoot.replicated.com", Version: "v1beta1", Resource: "collectorjobs"}

var collectorjobsKind = schema.GroupVersionKind{Group: "troubleshoot.replicated.com", Version: "v1beta1", Kind: "CollectorJob"}

// Get takes name of the collectorJob, and returns the corresponding collectorJob object, and an error if there is any.
func (c *FakeCollectorJobs) Get(name string, options v1.GetOptions) (result *v1beta1.CollectorJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(collectorjobsResource, c.ns, name), &v1beta1.CollectorJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CollectorJob), err
}

// List takes label and field selectors, and returns the list of CollectorJobs that match those selectors.
func (c *FakeCollectorJobs) List(opts v1.ListOptions) (result *v1beta1.CollectorJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(collectorjobsResource, collectorjobsKind, c.ns, opts), &v1beta1.CollectorJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1beta1.CollectorJobList{ListMeta: obj.(*v1beta1.CollectorJobList).ListMeta}
	for _, item := range obj.(*v1beta1.CollectorJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested collectorJobs.
func (c *FakeCollectorJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(collectorjobsResource, c.ns, opts))

}

// Create takes the representation of a collectorJob and creates it.  Returns the server's representation of the collectorJob, and an error, if there is any.
func (c *FakeCollectorJobs) Create(collectorJob *v1beta1.CollectorJob) (result *v1beta1.CollectorJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(collectorjobsResource, c.ns, collectorJob), &v1beta1.CollectorJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CollectorJob), err
}

// Update takes the representation of a collectorJob and updates it. Returns the server's representation of the collectorJob, and an error, if there is any.
func (c *FakeCollectorJobs) Update(collectorJob *v1beta1.CollectorJob) (result *v1beta1.CollectorJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(collectorjobsResource, c.ns, collectorJob), &v1beta1.CollectorJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CollectorJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCollectorJobs) UpdateStatus(collectorJob *v1beta1.CollectorJob) (*v1beta1.CollectorJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(collectorjobsResource, "status", c.ns, collectorJob), &v1beta1.CollectorJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CollectorJob), err
}

// Delete takes name of the collectorJob and deletes it. Returns an error if one occurs.
func (c *FakeCollectorJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(collectorjobsResource, c.ns, name), &v1beta1.CollectorJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCollectorJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(collectorjobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1beta1.CollectorJobList{})
	return err
}

// Patch applies the patch and returns the patched collectorJob.
func (c *FakeCollectorJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1beta1.CollectorJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(collectorjobsResource, c.ns, name, pt, data, subresources...), &v1beta1.CollectorJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1beta1.CollectorJob), err
}
