apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: loadbalancer
spec:
  remoteCollectors:
    - tcpLoadBalancer:
        collectorName: loadbalancer
        port: 7443
        address: 10.128.0.29:7444
  analyzers:
    - tcpLoadBalancer:
        collectorName: loadbalancer
        outcomes:
          - fail:
              when: "invalid-address"
              message: The Load Balancer address is not valid.
          - fail:
              when: "connection-refused"
              message: Connection to port 7443 via load balancer was refused.
          - fail:
              when: "address-in-use"
              message: Another process was already listening on port 7443.
          - fail:
              when: "connection-timeout"
              message: Timed out connecting to port 7443 via load balancer. Check your firewall.
          - fail:
              when: "error"
              message: Unexpected port status
          - pass:
              when: "connected"
              message: Successfully connected to port 7443 via load balancer
          - warn:
              message: Unexpected port status
