apiVersion: troubleshoot.sh/v1beta3
kind: SupportBundle
metadata:
  name: postgres-support-bundle
spec:
  collectors:
    - postgres:
        collectorName: main-database
        uri:
          valueFrom:
            secretKeyRef:
              name: postgres-connection
              key: connection-uri
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-connection
type: Opaque
stringData:
  connection-uri: "postgresql://myuser:mypassword@postgres.default.svc:5432/mydb?sslmode=require"
