apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: all-windows-host-collectors
spec:
  hostCollectors:
    # System Info Collectors
    - cpu: {}
    - memory: {}
    - time: {}
    - hostOS: {}
    - ipv4Interfaces: {}

    # Disk Usage
    - diskUsage:
        collectorName: c-drive
        path: C:\
    - diskUsage:
        collectorName: temp
        path: C:\temp

    # Certificate Collectors
    - certificate:
        collectorName: test-cert
        certificatePath: C:\certs\server.crt
        keyPath: C:\certs\server.key
    - certificatesCollection:
        collectorName: certs-collection
        paths:
          - C:\certs

    # Network Tests
    - tcpPortStatus:
        collectorName: rdp-port
        port: 3389
    - tcpPortStatus:
        collectorName: http-port
        port: 80
    - udpPortStatus:
        collectorName: dns-port
        port: 53
    - tcpConnect:
        collectorName: localhost-rdp
        address: 127.0.0.1:3389
        timeout: 5s
    - tcpLoadBalancer:
        collectorName: lb-test
        address: 127.0.0.1
        port: 8080
        timeout: 10s
    - httpLoadBalancer:
        collectorName: http-lb-test
        address: http://127.0.0.1:8080
        port: 8080
        timeout: 10s
    - http:
        collectorName: google
        get:
          url: https://www.google.com
    - http:
        collectorName: localhost-health
        get:
          url: http://localhost:8080/health
    - dns:
        collectorName: dns-google
        hostnames:
          - google.com
    - dns:
        collectorName: dns-localhost
        hostnames:
          - localhost
    - subnetAvailable:
        collectorName: subnet-check
        CIDRRangeAlloc: 10.0.0.0/16
        desiredCIDR: 24

    # Custom Commands (Windows)
    - run:
        collectorName: systeminfo
        command: "systeminfo"
    - run:
        collectorName: ipconfig
        command: "ipconfig"
        args: ["/all"]
    - run:
        collectorName: tasklist
        command: "tasklist"
    - run:
        collectorName: netstat
        command: "netstat"
        args: ["-ano"]
    - run:
        collectorName: hostname
        command: "hostname"
    - run:
        collectorName: route-print
        command: "route"
        args: ["print"]
    - run:
        collectorName: ps-version
        command: "powershell"
        args: ["-Command", "$PSVersionTable"]
    - run:
        collectorName: windows-version
        command: "powershell"
        args: ["-Command", "Get-ComputerInfo | Select-Object WindowsVersion, OsArchitecture"]
    - run:
        collectorName: disk-info
        command: "powershell"
        args: ["-Command", "Get-PSDrive -PSProvider FileSystem"]

    # Copy Files (Windows)
    - copy:
        collectorName: hosts-file
        path: C:\Windows\System32\drivers\etc\hosts
    - copy:
        collectorName: windows-logs
        path: C:\Windows\System32\winevt\Logs\System.evtx
