apiVersion: troubleshoot.replicated.com/v1beta1
kind: Analyzer
metadata:
  name: a
spec:
  analyzers:
    - distribution:
        outcomes:
          - fail:
              when: "= dockerdesktop"
              message: "docker for desktop is not allowed"
          # - fail:
          #     when: "microk8s"
          #     message: "mickrk8s is not prod"
          - fail:
              when: "!= openshift"
              message: "this should fail on anything other than openshift"
          - warn:
              when: "!= eks"
              message: "YMMV on not eks"
          - pass:
              message: "good work"


