on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main

jobs:
  compile-supportbundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - uses: actions/checkout@v3
      - run: make generate support-bundle
      - uses: actions/upload-artifact@v3
        with:
          name: support-bundle
          path: bin/support-bundle

  validate-supportbundle-e2e-go-test:
    runs-on: ubuntu-latest
    needs: compile-supportbundle
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19"
      - name: setup env
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
        shell: bash
      - uses: actions/checkout@v3
      - name: Download support bundle binary
        uses: actions/download-artifact@v3
        with:
          name: support-bundle
          path: bin/
      - run: chmod +x bin/support-bundle
      - run: make support-bundle-e2e-go-test
